// Generated by CoffeeScript 1.7.1
(function() {
  var filloutTable, setup;

  filloutTable = function(json) {
    var cell, row, t, trackname, _results;
    if (json === void 0) {
      return $.getJSON('/log', filloutTable);
    } else {
      t = $('#associate-callsign-table');
      t.html('');
      _results = [];
      for (trackname in json) {
        row = $('<tr>');
        row.append('<td>' + trackname + '</td>');
        cell = $('<td>');
        cell.append(json[trackname]);
        row.append(cell);
        _results.push(t.append(row));
      }
      return _results;
    }
  };

  setup = function() {
    return filloutTable();
  };

  $(document).ready(function() {
    return setup();
  });

}).call(this);
